version: '2'
services:
    grib2json:
        container_name: grib2json
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
          - .:/usr/src/app
          - ./docker-entrypoint.sh:/docker-entrypoint.sh
        working_dir: /usr/src/app
        entrypoint: /docker-entrypoint.sh
